"use client";
import {FormEvent,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {isSupabaseConfigured,supabase} from "@/lib/supabase";
export default function CadastroPage(){
  const router=useRouter();
  const [name,setName]=useState(""),[username,setUsername]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();if(!/^[A-Za-z0-9_!*/.+-]{3,24}$/.test(username)){setMessage("O @ deve ter de 3 a 24 caracteres, sem espaços. Use letras, números ou _ ! * / . + -.");return;}if(password.length<6){setMessage("A senha precisa ter pelo menos 6 caracteres.");return;}if(password!==confirm){setMessage("As senhas não coincidem.");return;}if(!isSupabaseConfigured){setMessage("Configure o arquivo .env.local antes de cadastrar.");return;}setLoading(true);const{error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name,username,class_name:"2º Informática"}}});setLoading(false);if(error){setMessage(error.message);return;}setMessage("Conta criada. Verifique seu e-mail, se necessário.");setTimeout(()=>router.push("/login"),1200);}
  const input="mt-2 w-full rounded-lg border border-white/10 bg-black/20 px-4 py-3 text-white";
  return <main className="min-h-screen bg-[#11100f] px-6 py-10"><section className="mx-auto max-w-2xl"><Link href="/login" className="text-sm text-[#ffd19a]">← Voltar para login</Link><h1 className="mt-6 text-4xl font-black">Criar conta</h1><p className="mt-2 text-[#b9aaa0]">Entre na comunidade escolar do Bonfire.</p><form onSubmit={submit} className="mt-8 grid gap-4 rounded-2xl border border-white/10 bg-white/[.045] p-6"><label className="text-sm text-[#b9aaa0]">Nome completo<input required value={name} onChange={e=>setName(e.target.value)} className={input}/></label><label className="text-sm text-[#b9aaa0]">Nome de usuário<input required pattern="[A-Za-z0-9_!*/.+-]{3,24}" maxLength={24} autoCapitalize="none" value={username} onChange={e=>setUsername(e.target.value)} className={input}/><span className="mt-1 block text-xs">Sem espaços; use letras, números ou _ ! * / . + -.</span></label><label className="text-sm text-[#b9aaa0]">E-mail escolar<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className={input}/></label><div className="grid gap-4 md:grid-cols-2"><label className="text-sm text-[#b9aaa0]">Senha<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} className={input}/></label><label className="text-sm text-[#b9aaa0]">Confirmar senha<input required type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} className={input}/></label></div>{message&&<p className="rounded-lg border border-white/10 bg-white/5 p-3 text-sm">{message}</p>}<button disabled={loading} className="rounded-full bg-[#ff8a3d] px-5 py-3 font-bold text-[#21140e]">{loading?"Criando conta...":"Criar conta"}</button></form></section></main>;
}
