"use client";
import {FormEvent,useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";
type Person={id:string;display_name:string|null;username:string|null};
export default function ChatGroupCreator(){
  const [open,setOpen]=useState(false),[name,setName]=useState(""),[description,setDescription]=useState(""),[privateGroup,setPrivateGroup]=useState(false),[people,setPeople]=useState<Person[]>([]),[members,setMembers]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{if(open)void supabase.from("profiles").select("id,display_name,username").order("display_name").limit(100).then(({data})=>setPeople((data||[]) as Person[]));},[open]);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");const result=await supabase.rpc("create_chat_group",{group_name:name,group_description:description,private_group:privateGroup,member_ids:privateGroup?members:[]});setBusy(false);if(result.error){setError("Não foi possível criar o grupo. A atualização do banco pode ainda não ter sido aplicada.");return;}window.location.reload();}
  return <div className="mb-5"><button type="button" onClick={()=>setOpen(value=>!value)} className="w-full rounded-full bg-[#ff8a3d] px-4 py-3 font-bold text-[#21140e]">{open?"Cancelar":"Criar grupo"}</button>{open&&<form onSubmit={submit} className="mt-4 grid gap-3 rounded-xl border border-white/10 p-4"><label className="text-sm">Nome<input required minLength={2} maxLength={60} value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded-lg border border-white/15 bg-black/20 p-3"/></label><label className="text-sm">Descrição<input maxLength={240} value={description} onChange={e=>setDescription(e.target.value)} className="mt-1 w-full rounded-lg border border-white/15 bg-black/20 p-3"/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={privateGroup} onChange={e=>setPrivateGroup(e.target.checked)}/> Grupo privado</label>{privateGroup&&<fieldset className="max-h-48 overflow-y-auto rounded-lg border border-white/10 p-3"><legend className="text-sm font-bold">Convidar pessoas</legend>{people.map(person=><label key={person.id} className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={members.includes(person.id)} onChange={e=>setMembers(current=>e.target.checked?[...current,person.id]:current.filter(id=>id!==person.id))}/>{person.display_name||person.username||"Usuário"}</label>)}</fieldset>}{error&&<p className="text-sm text-red-200">{error}</p>}<button disabled={busy||name.trim().length<2} className="rounded-full border border-[#ff8a3d]/50 p-3 font-bold text-[#ffd19a] disabled:opacity-50">{busy?"Criando…":"Criar agora"}</button></form>}</div>;
}
