"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase";
import {socialHandle,SocialAuthor} from "@/lib/social";
type Comment={id:string;content:string;created_at:string;author_id:string;parent_id:string|null;author:SocialAuthor|null};
export default function SparkThread({postId,userId,locked,onChanged}:{postId:string;userId:string;locked:boolean;onChanged:()=>void}){
  const [items,setItems]=useState<Comment[]>([]),[replyTo,setReplyTo]=useState<string|null>(null),[text,setText]=useState(""),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);const comments=await supabase.from("comments").select("id,content,created_at,author_id,parent_id").eq("post_id",postId).order("created_at");if(comments.error){setError("Não foi possível abrir a conversa. A atualização de threads pode ainda não ter sido aplicada.");setLoading(false);return;}const ids=[...new Set((comments.data||[]).map(x=>x.author_id))];const profiles=ids.length?await supabase.from("profiles").select("id,username,display_name,temporary_tag,avatar_url").in("id",ids):{data:[],error:null};const map=new Map((profiles.data||[]).map(p=>[p.id,p]));setItems((comments.data||[]).map(c=>({...c,author:map.get(c.author_id)||null})) as Comment[]);setError("");setLoading(false);},[postId]);
  useEffect(()=>{void load();const channel=supabase.channel("spark-thread:"+postId).on("postgres_changes",{event:"*",schema:"public",table:"comments",filter:"post_id=eq."+postId},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel);};},[load,postId]);
  async function submit(e:FormEvent){e.preventDefault();const content=text.trim();if(content.length<2)return;setSending(true);const result=await supabase.from("comments").insert({post_id:postId,author_id:userId,parent_id:replyTo,content});setSending(false);if(result.error){setError("Não foi possível comentar agora.");return;}setText("");setReplyTo(null);await load();onChanged();}
  function branch(parent:string|null,depth=0):React.ReactNode{return items.filter(x=>x.parent_id===parent).map(item=><article key={item.id} className={`mt-2 rounded-xl border border-white/10 bg-black/10 p-4 ${depth?"ml-4 md:ml-8":""}`}><div className="flex flex-wrap justify-between gap-2"><Link href={`/pessoas/${item.author_id}`} className="font-bold">{socialHandle(item.author)}</Link><time className="text-xs text-[#7d7068]">{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(item.created_at))}</time></div><p className="mt-2 whitespace-pre-wrap break-words">{item.content}</p>{!locked&&<button type="button" onClick={()=>{setReplyTo(item.id);setText("");}} className="mt-2 text-xs text-[#ffd19a]">Responder</button>}{branch(item.id,depth+1)}</article>);}
  return <section className="mt-4 border-t border-white/10 pt-4" onClick={e=>e.stopPropagation()}><h3 className="font-bold">Conversa</h3>{loading?<p className="mt-3 text-sm text-[#b9aaa0]">Carregando comentários…</p>:<div className="mt-3">{branch(null)}{!items.length&&<p className="text-sm text-[#b9aaa0]">Nenhum comentário ainda.</p>}</div>}{!locked&&<form onSubmit={submit} className="mt-4">{replyTo&&<p className="mb-2 text-xs text-[#ffd19a]">Respondendo a um comentário · <button type="button" className="underline" onClick={()=>setReplyTo(null)}>cancelar</button></p>}<div className="flex gap-2"><input aria-label={replyTo?"Responder comentário":"Comentar na faísca"} value={text} onChange={e=>setText(e.target.value)} maxLength={2000} placeholder={replyTo?"Escreva uma resposta…":"Comente nesta faísca…"} className="min-w-0 flex-1 rounded-full border border-white/15 bg-black/20 px-4 py-3"/><button disabled={sending||text.trim().length<2} className="rounded-full bg-[#ff8a3d] px-4 font-bold text-[#21140e] disabled:opacity-50">Enviar</button></div></form>}{error&&<p role="alert" className="mt-3 text-sm text-red-200">{error}</p>}</section>;
}
